version: '3.9'

services:
  db:
    image: postgres:15-alpine
    container_name: beehive-postgres
    restart: always
    env_file: .env  
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: beehive
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d beehive"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata: